### ISSUE TITLE
ModuleNotFoundError: No module named 'guiqwt.histogram2d'

### ISSUE THREAD

**Issue by JianboHIT** [PierreRaybaut/guiqwt#84] opened 2020-08-26 14:14 UTC
The latest version of the program is not available. When I try to run tests program, a ModuleNotFoundError is throw:

>>> from guiqwt import tests
>>> tests.run()
Module 'guiqwt.image': missing C extension
try running :python setup.py build_ext --inplace -c mingw32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiqwt\tests\__init__.py", line 17, in run
    run_testlauncher(guiqwt)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guidata\guitest.py", line 179, in run_testlauncher
    win = TestLauncherWindow(package)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guidata\guitest.py", line 147, in __init__
    tests = get_tests(test_package)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guidata\guitest.py", line 52, in get_tests
    _temp = __import__(test_package.__name__, fromlist=[module_name])
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiqwt\tests\benchmarks.py", line 20, in <module>
    from guiqwt.plot import CurveWindow, ImageWindow
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiqwt\plot.py", line 131, in <module>
    from guiqwt.image import ImagePlot
  File "C:\Users\acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiqwt\image.py", line 191, in <module>
    from guiqwt.histogram2d import histogram2d, histogram2d_func
ModuleNotFoundError: No module named 'guiqwt.histogram2d'

**Comment by kevinanewman** [comment] 2021-04-29 18:01
I have the same issue

**Comment by PierreRaybaut** [comment] 2022-06-05 07:25
Duplicate of #88

**Closed by PierreRaybaut** 2022-06-05 07:25 UTC
