### ISSUE TITLE
32bit wheel on PyPI includes 64bit libraries

### ISSUE THREAD

**Issue by pa-eidam** [PierreRaybaut/guiqwt#69] opened 2017-02-03 06:49 UTC
Affected wheel: guiqwt-3.0.3-cp35-cp35m-win32.whl
Libraries: _scaler.cp35-win_amd64.pyd, histogram2d.cp35-win_amd64.pyd, mandelbrot.cp35-win_amd64.pyd
Source: PyPI (pypi.python.org/pypi/guiqwt)

**Comment by PierreRaybaut** [comment] 2022-06-05 10:17
Fixed - duplicate of issue #88

**Closed by PierreRaybaut** 2022-06-05 10:17 UTC
