### ISSUE TITLE
Issue with pyqt5 and spydererlib

### ISSUE THREAD

**Issue by JulienNic0las** [PierreRaybaut/guiqwt#72] opened 2017-05-16 11:39 UTC
Hi,

After a fresh install of guiqwt (so version 3.0.3 via pip) on Anaconda 3, I cannot run tests example:

`from guiqwt import tests
tests.run()

>>>assert os.environ['QT_API'] in ('pyqt', 'pyside')
>>>AssertionError:`

I can provide a full stacktrace of the error message at request. I understand that

**Comment by PierreRaybaut** [comment] 2022-06-05 10:18
Duplicate of #73

**Closed by PierreRaybaut** 2022-06-05 10:18 UTC
